"""Extract the Prologue from 'Second Light of March.pdf' and build a story.json
so the pipeline can produce a PDF + audiobook for just that section (a taste test).
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

PDF = r"d:\Writer\Second Light of March.pdf"
OUT = r"d:\Writer\output\prologue-taste\story.json"

# Faithful transcription of the Prologue (pages 3-4 of the sample PDF)
PARAGRAPHS = [
    "Four months have elapsed \u2014 a statistically modest but emotionally significant "
    "interval \u2014 and I find myself conducting a rather inconvenient audit of my current "
    "psychological state. Life, by most objective metrics, appears to be progressing "
    "satisfactorily. And yet, a persistent subroutine in my cognitive architecture \u2014 call it "
    "my shadow-self \u2014 keeps whispering contrarian data points: that nothing has fundamentally "
    "changed, that the apparent flourishing is merely an optical illusion generated by my own "
    "desperate need to believe otherwise.",
    "The human mind is a fascinatingly inefficient piece of biological engineering. In one "
    "respiratory cycle, it can reduce the entire universe to ash and particulate matter. In the "
    "very next, it can conjure a single sunflower turning its face toward the sun, and suddenly "
    "the apocalypse feels manageable. This July has been a deluge \u2014 a showering, a blessing, "
    "a cascading of H\u2082O molecules, whichever semantic label you prefer. They all register "
    "identically on my sensory apparatus, though intellectually I concede there ought to be a "
    "discernible difference.",
    "The woman to whom I promised a statistically improbable future has terminated all "
    "communication channels, having calculated that our trajectory had reached its inevitable "
    "terminus. I respect her conclusion. The mathematics of her decision are, regrettably, sound.",
    "An overwhelming surge of neurochemical activity has taken root in my limbic system, casting "
    "a measurable shadow over the rhythms of my daily functioning. I hypothesize that by "
    "externalizing these data points \u2014 by unloading these burdens onto the page \u2014 I may "
    "finally clear the signal-to-noise ratio and perceive the world with something approaching "
    "clarity once more.",
    "A note on methodology: I have chosen to veil the identities of the individuals who populate "
    "these pages, replacing their given names with carefully selected aliases. This deliberate "
    "distance serves a dual purpose. It safeguards their privacy \u2014 a non-negotiable "
    "constraint \u2014 and it preserves my own cognitive stability, allowing me to document the "
    "truth without shattering the delicate silence that surrounds their lives.",
]

# Hand-tuned image prompts + emotions for each prologue paragraph (photorealistic taste)
IMAGE_PROMPTS = [
    "a man in his thirties staring out a rain-streaked window in a dim apartment, city lights bokeh, July evening, melancholic cinematic photography",
    "a single sunflower turning toward pale sunlight on a windowsill, raindrops on glass, soft focus, still life",
    "an empty chair and a phone on a wooden table, soft warm lamp light, quiet melancholy still life, photorealistic",
    "a man writing by lamplight at a desk at night, stacks of paper, deep shadows, intimate mood, cinematic photo",
    "a closed leather journal and a fountain pen on a desk, dust motes in window light, serene stillness, photorealistic",
]
EMOTIONS = ["somber", "neutral", "sad", "somber", "calm"]


def clean_pdf_text():
    return PARAGRAPHS


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    paras = clean_pdf_text()
    if not paras:
        print("No paragraphs extracted!")
        return 1
    for i, p in enumerate(paras, 1):
        print(f"  P{i}: {p[:80]}...")

    story = {
        "title": "Second Light of March - Prologue (taste)",
        "author": "",
        "cover_prompt": ("a contemplative man silhouetted at a rain-streaked window in a city "
                         "at dusk, cinematic photorealistic, melancholic mood, no text"),
        "prologue": {
            "title": "Le Prologue du Silence",
            "paragraphs": paras,
            "image_prompts": IMAGE_PROMPTS[:len(paras)],
            "emotions": EMOTIONS[:len(paras)],
        },
        "sections": [],
        "epilogue": None,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(story, f, ensure_ascii=False, indent=2)
    print(f"\nSaved {OUT} ({len(paras)} paragraphs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
